### ISSUE TITLE
Taking suffocation damage while shrunken to 0.1

### ISSUE THREAD

**Issue by NillerMedDild** [gigabit101/Shrink#39]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2743

Shrinking to size 0.1 causes the player to go inside the block it stands on, and take suffocation damage. It also appears that the player enters swim mode.

Screenshot of standing still on grass:
![billede](https://user-images.githubusercontent.com/21295394/125845130-1d82e9b4-17f6-425b-867f-040f3c96b4d9.png)

**Comment by gigabit101** [comment]
You should not be able to shrink down that far unless the config file has been edited, the default value is 0.21F https://github.com/gigabit101/Shrink/blob/master/src/main/java/net/gigabit101/shrink/config/ShrinkConfig.java#L51

**Comment by gigabit101** [comment]
This could also be caused by the config not being regenerated after the latest update, If the issue continues after the config has been regenerated please do let me know.

**Comment by NillerMedDild** [comment]
My config looks like this:

```toml
#Set the amount of power required to use use the personal shrinking device
setPowerUsage = 5000
#Set to true to enable power requirements for personal shrinking device
enablePowerRequirements = true
#Set the amount of power the personal shrinking device can store
setShrinkingDeviceCapacity = 100000
#Set to false to disable mobs being put in bottles
enableMobBottles = true
#Set the max size a player can grow too
#Range: 0.0 ~ 100.0
maxSize = 10.0
#Set the min size a player can shrink too
#Range: 0.21 ~ 100.0
minSize = 0.21
```
